# site configuration

exclude: [Gemfile, Gemfile.lock, README.md, LICENSE, Makefile, README.md]
permalink: pretty

repository: hdiresearch/hdiresearch.github.io

author: Richard Mortier
settings:
  analytics:
    id: UA-45397197-1
    name: hdiresearch.org
