# site configuration

exclude: [Gemfile, Gemfile.lock, README.md, LICENSE, Makefile, README.md]
permalink: pretty
markdown: kramdown

author: Richard Mortier
settings:
  github: hdiresearch/hdiresearch.github.io
  analytics:
    id: UA-45397197-1
    name: hdiresearch.org
